steps:
# build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/astute-winter-257006','.']
  #env:
  #- 'DOCKER_API_VERSION=1.41'
# Push the image to the repository
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/$PROJECT_ID/astute-winter-257006']
# Deploy the image to the GKE Cluster
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=gke.yaml
  - --image=gcr.io/$PROJECT_ID/astute-winter-257006
  - --location=us-central1-a
  - --cluster=gcp-devops-gke
  - --namespace=gcp-devops-prod
options:
  logging: CLOUD_LOGGING_ONLY